# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Akshay Chaudhari
email: akshaychaudhari@gmail.com
description: Post-Doctoral Scholar, Stanford University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Logo settings
logo-image-url: images/logo.png
font-awesome-icon-logo:

# Social settings
github_username: akshaysc
twitter_username: 
facebook_URL: akshaysc
instagram_username: 
dribbble_username: 
500px_username: 
phone: 555-5555

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes
